# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    custom_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - waist
      - shoulder
      - elbow
      - forearm_roll
      - wrist_angle
      - wrist_rotate
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
custom_controller:
  ros__parameters:
    joints:
      []
    command_interfaces:
      []
    state_interfaces:
      []